### ISSUE TITLE
possible interaction with Socrata's UNDP website

### ISSUE THREAD

**Issue by danhammer** [SDG-data/SDGs#33]
Check out [this website](http://mdg-sdg3d.undp.org/).  It is powered by a bunch of pretty good APIs, including these examples:

[http://mdg-sdg3d.undp.org/en/country-database/countries/ken/goals/2/indicators/429.json](http://mdg-sdg3d.undp.org/en/country-database/countries/ken/goals/2/indicators/429.json)

Note that you can change `ken` in the URL to, say, `ago` to switch countries from Kenya to Angola.  There are also a few other endpoints that are neat, including this one that tracks the number of SDGs involving each country:

[http://mdg-sdg3d.undp.org/en/country-database.json?iso=ROU](http://mdg-sdg3d.undp.org/en/country-database.json?iso=ROU)

Seems worth thinking about, maybe building visualizations or something.

**Comment by pythagoraswitch** [comment]
Thank you for the note, @danhammer! I also saw the website at the GPSDDA meeting and took notes as well. Great point -- would be great to incorporate it in some way. cc @brunosan

**Comment by liang3404814** [comment]
Hi @danhammer and @pythagoraswitch, those are great finds!

While you are free to play around with the json endpoint you found, it is meant to be consumed by the site itself, and is thus subject to changes without notification. We don't want you to write something amazing to access the data through this endpoint, and then becomes broken :cry: because we changed it! 

For this reason, I recommend you to check out the [Socrata dataset](https://indicators.undp.org/dataset/Combined-Countries-Data/tqft-752a). The dataset exposes an [API](https://dev.socrata.com/consumers/getting-started.html) that allows you to query the dataset with filters and queries. In fact, it is this very API that powers the the site. A (machine-generated) documentation can be accessed under [Export / SODA API / API Docs](https://dev.socrata.com/foundry/#/indicators.undp.org/c4cj-8k3x)

Thank you!

**Comment by brunosan** [comment]
Thank @danhammer for the discovery and sharing, and thank you @liang3404814 for the clarification and pointer to the API. UNDP data is mostly available also via Bank's API, so I think we'll have several sources when we start pulling live data. (Excited for that time to come asap!)

Closing as not actionable right now.

**Comment by jeffkaplan88** [comment]
Bruno,
This MDG data from UNDP may not be available via the Bank or any other source.  It has been scraped from 15 years of national MDG reports -- all in PDFs -- sent to UNDP from countries via their country offices.  Not sure this raw data exists anywhere else.
- Jeff
